### ISSUE TITLE
Why use Strings instead of System.out.print for Hello, World! ? 

### ISSUE THREAD

**Issue by PhannyGG** [Vonaclast/JavaLearning#3]
Title ^

**Comment by mazunki** [comment]
The idea is to declare String variables to use inside the method, instead of printing the words directly. 
It's useful when your output depends on some other input, for example.

**Comment by Vonaclast** [comment]
When you use the printing method, you can either directly pass it a String value, such as:

System.out.print("Hello, world!");

Or, alternatively, you can pass it variables.

Say you have 2 String variables, such as:

String a = "Hello";
String b = "World";

You can call the method, and as an argument, pass it the two variables, such as:

System.out.print(a + b);

This, however, will print the following to the console:

HelloWorld

In order to make it look good, you would change the syntax in this way:

System.out.print(a + " " + b + "!")

**Comment by PhannyGG** [comment]
Yeah, so why are we using String variables which is more work, when we could use System.out.print? :O

**Comment by Vonaclast** [comment]
Mostly to practice - these exercises are not meant to be _optimal_, they are meant to be educational.

**Comment by Th3Trickster** [comment]
A bad practice is to use multiple variables when you don't have to because this uses more memory doing it this way, like the example Vonaclast gave of the other way you could do it with 2 String variables is bad practice, no offense to Vonaclast because he was just showing you that there are other ways.  Just use the System.out.println()
